# Change anything you need to in this file, including the base image.
#FROM python:2.7
#
#ADD . /app
#WORKDIR /app
#
#CMD ["python", "-m", "SimpleHTTPServer", "9090"]

FROM golang:1.9.2
WORKDIR /go/src/SpaceX
COPY . /go
RUN go install .
#CMD ["/go/src/SpaceX/wait-for-postgres.sh", "postgresdb:5432", "/go/bin/SpaceX"]
CMD ["/go/bin/SpaceX"]

